# Generated by Django 4.1.4 on 2023-01-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wgfapp', '0004_category_member_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wgfapp.category'),
        ),
    ]
