# Generated by Django 4.1.4 on 2023-01-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgfapp', '0005_remove_member_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
