# Generated by Django 4.1.4 on 2023-01-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgfapp', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
