# Generated by Django 4.1.4 on 2023-01-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgfapp', '0011_alter_post_author_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=5000),
        ),
    ]
